//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: demo.proto
// Note: requires additional types generated from: NestDTO.proto
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"People")]
  public partial class People : global::ProtoBuf.IExtensible
  {
    public People() {}
    
    private PBMessage.NestDTO _nestDTO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nestDTO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.NestDTO nestDTO
    {
      get { return _nestDTO; }
      set { _nestDTO = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private float _height;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float height
    {
      get { return _height; }
      set { _height = value; }
    }
    private bool _isMan;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isMan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isMan
    {
      get { return _isMan; }
      set { _isMan = value; }
    }
    private byte[] _bbb;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"bbb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] bbb
    {
      get { return _bbb; }
      set { _bbb = value; }
    }
    private double _speed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _hhh = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"hhh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> hhh
    {
      get { return _hhh; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"People2")]
  public partial class People2 : global::ProtoBuf.IExtensible
  {
    public People2() {}
    
    private PBMessage.People _pp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBMessage.People pp
    {
      get { return _pp; }
      set { _pp = value; }
    }
    private long _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _id2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id2
    {
      get { return _id2; }
      set { _id2 = value; }
    }
    private ulong _id3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id3
    {
      get { return _id3; }
      set { _id3 = value; }
    }
    private int _id4;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"id4", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int id4
    {
      get { return _id4; }
      set { _id4 = value; }
    }
    private long _id5;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"id5", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long id5
    {
      get { return _id5; }
      set { _id5 = value; }
    }
    private uint _id6;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"id6", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint id6
    {
      get { return _id6; }
      set { _id6 = value; }
    }
    private ulong _id7;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"id7", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong id7
    {
      get { return _id7; }
      set { _id7 = value; }
    }
    private int _id8;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"id8", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int id8
    {
      get { return _id8; }
      set { _id8 = value; }
    }
    private long _id9;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"id9", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long id9
    {
      get { return _id9; }
      set { _id9 = value; }
    }
    private PBMessage.People2.eTest _ee;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"ee", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PBMessage.People2.eTest ee
    {
      get { return _ee; }
      set { _ee = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"eTest")]
    public enum eTest
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Defaule", Value=0)]
      Defaule = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P1", Value=1)]
      P1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P2", Value=2)]
      P2 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Foo")]
  public partial class Foo : global::ProtoBuf.IExtensible
  {
    public Foo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _bar;
    [global::ProtoBuf.ProtoMember(126, IsRequired = true, Name=@"bar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bar
    {
      get { return _bar; }
      set { _bar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}